# Generated by Django 4.1 on 2022-08-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
        migrations.AddField(
            model_name='food',
            name='desc',
            field=models.CharField(default='', max_length=1000, verbose_name='description'),
            preserve_default=False,
        ),
    ]
