# Generated by Django 4.1 on 2022-08-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_food_description_food_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='username',
            field=models.CharField(default='awu', max_length=50),
            preserve_default=False,
        ),
    ]
