# Generated by Django 4.1 on 2022-09-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='/default/default-avatar.jpg', upload_to='avatars'),
        ),
    ]
